#+TITLE: Peer Review of Group 14 by Group 8
#+AUTHOR: Asier Galicia, Nicholas Zutt
#+DATE: 03.07.2020
#+OPTIONS: toc:nil

* Summary of the paper

  Microwave drivers are key electronic components of the architectures
that control experimental quantum processors. As quantum computers
scale up to sizes necessary for fault-tolerance, the use of
conventional room-temperature controls face new challenges. The paper
introduces and outlines approaches to scaling up control while
limiting delay times (by bringing control architectures closer to the
quantum processor) and keeping the number of control lines small
(scaling sub-linearly with number of qubits). A review of the
state-of-the-art mentions two key recent developments in cryogenic
microwave driver technology.

* Quality of the content

** Have all points been addressed?
   
*** Are microwave drivers required for solid-state qubits? (5)
    They mention three platforms, trasmon qubits, single electron semiconductor
    platforms and NV centres in diamond where microwave drivers are the go-to
    technology to perform single qubit rotations. However, they also mention a
    platform based on multiple electron spin qubits that can implement single
    qubit rotation by means of the Heisenberg exchange operation. 

    Given that they give a complete clear description of the use of microwaves
    in several platforms, we believe the authors deserve 5 points in this
    question.

*** Room temperature vs cryogenic MW drivers: pros and cons. (4.5)
    Room temperature long delays (10ns). Thermal load due to cabling posses a
    challenge in refrigerators. They do not give any pro for room temperature.
    In reference 2 they mention that room temperature electronics are much less
    limited in terms of power consumption. Microwave drivers at cryogenic stages
    avoid previous two problems but has the main disadvantage of its power being
    limited due to refrigerator efficiencies.

    
    
*** Advantages and requirements of FDMA. (5)
    In section 4 they give an overview of what FDMA is and why the role it plays
    when driving qubits. Some of the mentioned advantages are that FDMA reduces
    the number of microwave lines per qubits and that they do not restrict
    parallel operations as time-division multiple-access does. Regarding to the
    requirements, they mention both the wide range of frequencies required to
    address qubits and the bulky...
    
    Since they address explicitly both advantages and requirements of FDMA and
    they also give complementary information regarding to the constrains related
    to FDMA, we believe the authors deserve 5 points.

*** Implications of cryogenic electronics on MW driver design. (4)
    The answer to this question is related to the previous ones. he main
    implication is that there is a trade-off beteween power comsumption and
    performance. They also mention that the instruction set helps in this task
    by reducing the number of I/O lines.
    
    Robustness... They should have mentioned that characteristics of transistors
    change with cryogenic temperatures and that this is something that need to
    be taken into account in the design. Also, making clear the importance of
    the instruction set would have helped. They d

** Other important points that have been treated
   Universality on some quantum platforms (how ti implement multyqubit gates)
   
   State of the art very thoreough?

** Analysis of state of the art
   They analyze the implementation of the of two microwave controllers at
   cryogenic temperatures (4K). The main ideas are that optimizations are made
   to reduce power consumption but the power consumption is still one order of
   magnitude greater that the proposed limit by Bardin et al. Experiments
   performed with these controllers show that relaxation time and leakage was
   not deteriorated. Horse Ridge's pulse modulator is even improved with
   respect to Googleś one by introducing FDMA. Cross talk seems a problem but
   they do not go far into it.
   
   
   A quick overview of the microwave controller with its main components would
   have helped reading the state of the art section.
   
   vector modulation circuit?

* Clarity of the paper

** Structure
   4.5 / Microgave control of solid state qubits too long?
   No images that would be helpful at some places?

** Language
   4.5?
   
** Formatting
   5?

* Additional remarks
