#+TITLE: Peer Review of Group 14 by Group 8
#+AUTHOR: Asier Galicia, Nicholas Zutt
#+DATE: 03.07.2020
#+OPTIONS: toc:nil

* Summary of the paper

Microwave drivers are key electronic components of the architectures
that control experimental quantum processors. As quantum computers
scale up to sizes necessary for fault-tolerance, the use of
conventional room-temperature controls face new challenges. The paper
introduces and outlines approaches to scaling up control while
limiting delay times (by bringing control architectures closer to the
quantum processor) and keeping the number of control lines small
(scaling sub-linearly with number of qubits). A review of the
state-of-the-art mentions two key recent developments in cryogenic
microwave driver technology.

* Quality of the content

** Have all points been addressed?

*** Are microwave drivers required for solid-state qubits? (5)
    They mention three platforms, trasmon qubits, single electron
    semiconductor platforms and NV centres in diamond where microwave
    drivers are the go-to technology to perform single qubit
    rotations. The authors also mention a key disadvantage of using
    microwave drivers, which is the inherent trade-off between power
    consumption and gate speed, which becomes a greater challenge at
    cryogenic temperatures. However, they also mention a platform
    based on multiple electron spin qubits that can implement single
    qubit rotation by means of the Heisenberg exchange operation,
    raising the possibility that microwave drivers are not essential
    for qubit control in all hardware platforms.

    Given that they give a complete, clear description of the use of
    microwaves in several platforms, along with advantages and
    disadvantages, we believe the authors deserve 5 points in this
    question.

*** Room temperature vs cryogenic MW drivers: pros and cons. (4)
    The authors aptly outline the cons associated with room
    temperature microwave drivers, namely the delay (of up to 10ns)
    and thermal load caused by long cables running from the drivers to
    the processor. However, they do not explicitly mention advantages
    of room temperature drivers, which could be for example their
    simplicity or, as mentioned in Bardin /et al./, the fact that power
    consumption is not an issue at room temperature and one can use
    well established technology.
    
    Regarding the cryogenic drivers, the authors explain how low
    temperature drivers can address the main disadvantages associated
    with room temperature drivers. They also outline the challenges
    associated with implementing drivers at cryogenic temperatures.
    
    The authors did not specifically address the pros of room
    temperature drivers, but otherwise adequately explained the
    trade-offs between room temperature and cryogenic drivers. For
    this reason, we believe they deserve 4 points for this section.
    
*** Advantages and requirements of FDMA. (5)
    The authors give a good overview of FDMA and explain how it can
    take advantage of the tunability of qubit frequencies in order to
    address many qubits through one microwave line, while allowing for
    parallel operations (in contrast to time-division multiple-access
    approaches). 

    They also explain that implementing FDMA requires drivers with a
    larger range of frequencies available to them, as well as more
    complex read-out components. One final cost of FDMA is introducing
    potential cross-talk between qubits, something that will require
    more complex electronics to mitigate and control.
    
    Since they address explicitly both advantages and requirements of FDMA and
    they also give complementary information regarding to the constrains related
    to FDMA, we believe the authors deserve 5 points.

*** Implications of cryogenic electronics on MW driver design.

** Other important points that have been treated
The authors include a helpful discussion about implementing universal
gate sets on the various hardware platforms mentioned in their paper.

They also discuss why scalable electronics are necessary for the
implementation of a fully fault-tolerant quantum computer and mention
the threat of leakage outside the computational subspace, especially
for transmon qubits.

** Analysis of state of the art

The paper briefly includes the key results from Patra /et al/. and
presents the key developments of the Horse Ridge architecture in a
coherent and understandable way. However, aside from summarizing the
paper, more analysis of the results presented would have been very nice.

* Clarity of the paper

** Structure
The paper was properly structured and followed the order outlined in
the introduction, making it very easy to read. One suggestion would be
to have made the "Multiplexing Techniques" and "Microwave Drivers at
Cryogenic Temperatures" sections into sub-sections under a section
head entitled "Proposed Solutions". This would have made the structure
clearer and would have coincided better with the paper overview given
at the end of the introduction.

** Language
The language was very clear. A writing style of short, declarative
sentences broke down larger concepts effectively. The paper was
grammatically correct throughout with hardly any typos or other
mistakes. It was well-written and clearly proof-read several times.

** Formatting
There were no figures and the one equation in the paper was
well formatted with well defined symbols. The bibliography is well
formatted and complete with helpful links for references throughout
the paper and DOI links in the reference list, however the
bibliography does not appear in any particular order, contrary to
common approaches that organize entries by appearance in the text, or
name, or date.

* Additional remarks
Paper found an interesting way of illustrating the implications of
cryogenic temp on driver design using the current state of the art.
Accomplished a lot in one section.

In Section 5, the authors write that Bardin /et al./ use 0.01% as a
"benchmark" of the total error rate, which rendered the rest of the
paragraph unclear. We thought that their use of the word benchmark
meant that Bardin /et al./ were using an overall error rate of 0.01% as
the standard against which to compare their results. But, after
reviewing the paper, we suspect that they mean that Bardin /et al./
provided specifications corresponding to an overall rate of 0.01%.
This point could have been communicated more clearly.

There were sections of the paper where a figure could have
added greatly to explanations. We understand that the authors likely
chose not to include any figures due to the page limit, but we would
argue that figures can be a better and more efficient way of
explaining a concept or experimental setup than words alone.

Overall, the paper was clearly written, well-researched and showed
good understanding of the concepts and challenges in the development
of cryogenic microwave drivers.
