#+TITLE: Peer Review of Group 14 by Group 8
#+AUTHOR: Asier Galicia, Nicholas Zutt
#+DATE: 03.07.2020
#+OPTIONS: toc:nil

* Summary of the paper

Microwave drivers are key electronic components of the architectures
that control experimental quantum processors. As quantum computers
scale up to sizes necessary for fault-tolerance, the use of
conventional room-temperature controls face new challenges. The paper
introduces and outlines approaches to scaling up control while
limiting delay times (by bringing control architectures closer to the
quantum processor) and keeping the number of control lines small
(scaling sub-linearly with number of qubits). A review of the
state-of-the-art mentions two key recent developments in cryogenic
microwave driver technology.

* Quality of the content

** Have all points been addressed?

*** Are microwave drivers required for solid-state qubits?

*** Room temperature vs cryogenic MW drivers: pros and cons.

*** Advantages and requirements of FDMA.

*** Implications of cryogenic electronics on MW driver design.

** Other important points that have been treated

** Analysis of state of the art
The paper briefly includes the key results from Patra /et al/. and
presents the key developments of the Horse Ridge architecture in a
coherent and understandable way. However, aside from summarizing the
paper, more analysis of the results presented would have been very nice.

* Clarity of the paper

** Structure
The paper was properly structured and followed the order outlined in
the introduction, making it very easy to read. One suggestion would be
to have made the "Multiplexing Techniques" and "Microwave Drivers at
Cryogenic Temperatures" sections into sub-sections under a section
head entitled "Proposed Solutions". This would have made the structure
clearer and would have coincided better with the paper overview given
at the end of the introduction.

** Language
The language was very clear. A writing style of short, declarative
sentences broke down larger concepts effectively. The paper was
grammatically correct throughout with hardly any typos or other
mistakes. It was well-written and clearly proof-read several times.

** Formatting
There were no figures and the one equation in the paper was
well formatted with well defined symbols. The bibliography is well
formatted and complete with helpful links for references throughout
the paper and DOI links in the reference list.

* Additional remarks
Paper found an interesting way of illustrating the implications of
cryogenic temp on driver design using the current state of the art.
Accomplished a lot in one section.

There were however sections of the paper where a figure could have
added greatly to explanations. We understand that the authors likely
chose not to include any figures due to the page limit, but we would
argue that figures can be a better and more efficient way of
explaining a concept or experimental setup than words alone.
